ValueSet: NVDRSFirearmCaliberVS
Title: "VDOR - NVDRS Firearm Caliber Codes"
Id: nvdrs-firearm-caliber-vs
Description:  "NVDRS Coding Manual values for Firearm Caliber."
* ^experimental = true

* nvdrs-coding-manual-cs#FirearmCaliber556 "5.56 mm"
* nvdrs-coding-manual-cs#FirearmCaliber6 "6 mm"
* nvdrs-coding-manual-cs#FirearmCaliber635 "6.35 mm"
* nvdrs-coding-manual-cs#FirearmCaliber65 "6.5 mm"
* nvdrs-coding-manual-cs#FirearmCaliber7 "7 mm"
* nvdrs-coding-manual-cs#FirearmCaliber735 "7.35 mm"
* nvdrs-coding-manual-cs#FirearmCaliber75 "7.5 mm"
* nvdrs-coding-manual-cs#FirearmCaliber762 "7.62 mm"
* nvdrs-coding-manual-cs#FirearmCaliber763 "7.63 mm"
* nvdrs-coding-manual-cs#FirearmCaliber765 "7.65 mm"
* nvdrs-coding-manual-cs#FirearmCaliber8 "8 mm"
* nvdrs-coding-manual-cs#FirearmCaliber9 "9 mm"
* nvdrs-coding-manual-cs#FirearmCaliber10 "10 mm"
* nvdrs-coding-manual-cs#FirearmCaliber11 "11 mm"
* nvdrs-coding-manual-cs#FirearmCaliber17 ".17 in"
* nvdrs-coding-manual-cs#FirearmCaliber22 ".22 in"
* nvdrs-coding-manual-cs#FirearmCaliber221 ".221 in"
* nvdrs-coding-manual-cs#FirearmCaliber222 ".222 in"
* nvdrs-coding-manual-cs#FirearmCaliber223 ".223 in"
* nvdrs-coding-manual-cs#FirearmCaliber243 ".243 in"
* nvdrs-coding-manual-cs#FirearmCaliber25 ".25 in"
* nvdrs-coding-manual-cs#FirearmCaliber250 ".250 in"
* nvdrs-coding-manual-cs#FirearmCaliber256 ".256 in"
* nvdrs-coding-manual-cs#FirearmCaliber257 ".257 in"
* nvdrs-coding-manual-cs#FirearmCaliber264 ".264 in"
* nvdrs-coding-manual-cs#FirearmCaliber270 ".270 in"
* nvdrs-coding-manual-cs#FirearmCaliber280 ".280 in"
* nvdrs-coding-manual-cs#FirearmCaliber284 ".284 in"
* nvdrs-coding-manual-cs#FirearmCaliber30 ".30 in (including 30-06)"
* nvdrs-coding-manual-cs#FirearmCaliber300 ".300 in"
* nvdrs-coding-manual-cs#FirearmCaliber303 ".303 in"
* nvdrs-coding-manual-cs#FirearmCaliber308 ".308 in"
* nvdrs-coding-manual-cs#FirearmCaliber32 ".32 in"
* nvdrs-coding-manual-cs#FirearmCaliber338 ".338 in"
* nvdrs-coding-manual-cs#FirearmCaliber35 ".35 in"
* nvdrs-coding-manual-cs#FirearmCaliber351 ".351 in"
* nvdrs-coding-manual-cs#FirearmCaliber357 ".357 in"
* nvdrs-coding-manual-cs#FirearmCaliber36 ".36 in"
* nvdrs-coding-manual-cs#FirearmCaliber375 ".375 in"
* nvdrs-coding-manual-cs#FirearmCaliber38 ".38 in"
* nvdrs-coding-manual-cs#FirearmCaliber380 ".380 in"
* nvdrs-coding-manual-cs#FirearmCaliber40 ".40 in"
* nvdrs-coding-manual-cs#FirearmCaliber401 ".401 in"
* nvdrs-coding-manual-cs#FirearmCaliber405 ".405 in"
* nvdrs-coding-manual-cs#FirearmCaliber41 ".41 in"
* nvdrs-coding-manual-cs#FirearmCaliber44 ".44 in"
* nvdrs-coding-manual-cs#FirearmCaliber444 ".444 in"
* nvdrs-coding-manual-cs#FirearmCaliber455 ".455 in"
* nvdrs-coding-manual-cs#FirearmCaliber458 ".458 in"
* nvdrs-coding-manual-cs#FirearmCaliber460 ".460 in"
* nvdrs-coding-manual-cs#FirearmCaliber50 ".50 in"
* nvdrs-coding-manual-cs#FirearmCaliber54 ".54 in"
* nvdrs-coding-manual-cs#FirearmCaliber58 ".58 in"
* nvdrs-coding-manual-cs#FirearmCaliber60 ".60 in"
* nvdrs-coding-manual-cs#FirearmCaliber1000 "Undetermined whether .38 or .357"
* nvdrs-coding-manual-cs#FirearmCaliber1001 "Small, unspecified (<=32)"
* nvdrs-coding-manual-cs#FirearmCaliber1002 "Medium, unspecified (>32, <10mm/.40)"
* nvdrs-coding-manual-cs#FirearmCaliber1003 "Large, unspecified (>=10mm/.40)"
* nvdrs-coding-manual-cs#FirearmCaliber6666 "Other"
* nvdrs-coding-manual-cs#FirearmCaliber8888 "Not applicable (shotgun or unknown gun type)"
* $sct#261665006 "Unknown"