ValueSet: NVDRSWeaponTypeVS
Title: "NVDRS Weapon Type Valueset"
Id: nvdrs-weapon-type-vs
Description:  "Official NVDRS Coding Manual Weapon Type code ValueSet."
* ^experimental = true
* nvdrs-coding-manual-cs#WeaponType1 "Firearm"
* nvdrs-coding-manual-cs#WeaponType5 "Non-powder gun"
* nvdrs-coding-manual-cs#WeaponType6 "Sharp instrument"
* nvdrs-coding-manual-cs#WeaponType7 "Blunt instrument"
* nvdrs-coding-manual-cs#WeaponType8 "Poisoning"
* nvdrs-coding-manual-cs#WeaponType9 "Hanging, strangulation, suffocation"
* nvdrs-coding-manual-cs#WeaponType10 "Personal weapons"
* nvdrs-coding-manual-cs#WeaponType11 "Fall"
* nvdrs-coding-manual-cs#WeaponType12 "Explosive"
* nvdrs-coding-manual-cs#WeaponType13 "Drowning"
* nvdrs-coding-manual-cs#WeaponType14 "Fire or burns"
* nvdrs-coding-manual-cs#WeaponType15 "Shaking (e.g., shaken baby syndrome)"
* nvdrs-coding-manual-cs#WeaponType16 "Motor Vehicle, including buses, motorcycles"
* nvdrs-coding-manual-cs#WeaponType17 "Other transport vehicle, (e.g., trains, planes, boats)"
* nvdrs-coding-manual-cs#WeaponType18 "Intentional neglect, (e.g., starving a baby or oneself)"
* nvdrs-coding-manual-cs#WeaponType19 "Biological weapons"
* nvdrs-coding-manual-cs#WeaponType66 "Other (e.g., Taser, electrocution, nail gun, exposure to environment/weather)"
* $sct#261665006 "Unknown"