ValueSet: NVDRSFirearmTypeVS
Title: "VDOR - NVDRS Firearm Type Valueset"
Id: nvdrs-firearm-type-vs
Description: "NVDRS Coding Manual values for Weapon Type."
* ^experimental = true
* nvdrs-coding-manual-cs#FirearmType1 "Submachine Gun"
* nvdrs-coding-manual-cs#FirearmType2 "Handgun, Unknown Type"
* nvdrs-coding-manual-cs#FirearmType3 "Handgun, Pistol- Bolt Action"
* nvdrs-coding-manual-cs#FirearmType4 "Handgun, Pistol- Derringer"
* nvdrs-coding-manual-cs#FirearmType5 "Handgun, Pistol- Single Shot"
* nvdrs-coding-manual-cs#FirearmType6 "Handgun, Pistol- Semi-automatic"
* nvdrs-coding-manual-cs#FirearmType7 "Handgun, Revolver"
* nvdrs-coding-manual-cs#FirearmType8 "Rifle, Unknown Type"
* nvdrs-coding-manual-cs#FirearmType9 "Rifle, Automatic"
* nvdrs-coding-manual-cs#FirearmType10 "Rifle, Bolt Action"
* nvdrs-coding-manual-cs#FirearmType11 "Rifle, Lever Action"
* nvdrs-coding-manual-cs#FirearmType12 "Rifle, Pump Action"
* nvdrs-coding-manual-cs#FirearmType13 "Rifle, Semi-automatic"
* nvdrs-coding-manual-cs#FirearmType14 "Rifle, Single Shot"
* nvdrs-coding-manual-cs#FirearmType15 "Rifle-Shotgun Combination"
* nvdrs-coding-manual-cs#FirearmType16 "Shotgun, Unknown Type"
* nvdrs-coding-manual-cs#FirearmType17 "Shotgun, Automatic"
* nvdrs-coding-manual-cs#FirearmType18 "Shotgun, Bolt Action"
* nvdrs-coding-manual-cs#FirearmType19 "Shotgun, Double Barrel (Over/Under, Side by Side)"
* nvdrs-coding-manual-cs#FirearmType20 "Shotgun, Pump Action"
* nvdrs-coding-manual-cs#FirearmType21 "Shotgun, Semi-automatic"
* nvdrs-coding-manual-cs#FirearmType22 "Shotgun, Single Shot"
* nvdrs-coding-manual-cs#FirearmType23 "Long gun, Unknown type"
* nvdrs-coding-manual-cs#FirearmType66 "Other (e.g., handmade gun)"
* $sct#261665006 "Unknown"